Add some rules to regenerate parts of the build system if needed
flintlib/flint pull request #1527
Opened 2023-10-13 07:51 UTC by fingolfin

This is useful when e.g. editing configure.ac and then switching branches.

This does not yet regenerate src/config.h because that is slightly more complicated. 

And of course it should cover `flint.h` once/if we generate it (see PR #1449).

There is also issue #1526 which I first need to figure out. But I thought I'd open it as a draft so people can comment before I invest more time :-).

2023-11-16 14:24 UTC, albinahlback requested changes

2023-11-17 07:52 UTC, fingolfin commented on Makefile.in
> +	@./config.status $@
Good catch / good question. I don't have a strong reason either way. I am happy to treat them uniformly, one way or the other.

For now I made them all non-silent / verbose, as I think it is helpful for understanding what's going on when one does `make`.

2023-11-17 08:26 UTC, fingolfin commented
From my POV this is ready now.

2023-11-17 08:27 UTC, albinahlback approved these changes

2023-11-17 08:28 UTC, merged

2023-11-17 08:28 UTC, albinahlback commented
Thanks a lot for this!